### ISSUE TITLE
PHP errors in farming environment - configuration page empty

### ISSUE THREAD

**Issue by cultcom** [LotarProject/dokuwiki-template-bootstrap3#430]
We encountered several log messages regarding to PHP errors and a fatal error when we try to open the admin->configuration page inside a farm animal.

This warning pops up a lot in our logs:
```
ool dokuwiki: PHP Warning:  Invalid argument supplied for foreach() in /var/www/dokuwiki/lib/tpl/bootstrap3/tpl/page-tools.php on line 26
```

When we go to the configuration page within a farm animal we see this exception:
```
dokuwiki ool dokuwiki: PHP Fatal error:  Uncaught Error: Call to a member function getDescription() on null in /var/www/dokuwiki/lib/tpl/bootstrap3/Template.php:2264#012Stack trace:#012#0 /var/www/dokuwiki/lib/tpl/bootstrap3/Template.php(94): dokuwiki\template\bootstrap3\Template->normalizeContent('<h1 class="sect...')#012#1 /var/www/dokuwiki/inc/events.php(229): dokuwiki\template\bootstrap3\Template->contentHandler(Object(Doku_Event), NULL)#012#2 /var/www/dokuwiki/inc/events.php(70): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE')#012#3 /var/www/dokuwiki/inc/events.php(106): Doku_Event->advise_before(true)#012#4 /var/www/dokuwiki/inc/events.php(256): Doku_Event->trigger('ptln', true)#012#5 /var/www/dokuwiki/inc/template.php(85): trigger_event('TPL_CONTENT_DIS...', '\n<h1 class="sec...', 'ptln')#012#6 /var/www/dokuwiki/lib/tpl/bootstrap3/main.php(109): tpl_content(false)#012#7 /var/www/dokuwiki/inc/actions.php(27): include('/var/www/dokuwi...')#012#8 /var/www/dokuwiki/doku.php(120): act_dispatch()#012#9 {main}#012  thrown in /var/www/dokuwiki/lib/tpl/bootstrap3/Template.php on line 2264
```

The configuration page is rendered with an empty content box.

### Versions

* [Bootstrap3 Template] v2019-05-22
* [DokuWiki]  Release 2018-04-22b "Greebo"
* [PHP] 7.0 (Debian Stretch)

![Screenshot](https://user-images.githubusercontent.com/8860422/60955876-ff001100-a301-11e9-91a9-8fed3539b13c.png)

**Comment by LotarProject** [comment]
Hi @cultcom, i havepushed a fix for PHP Fatal and Warnings.

Please reinstall the template again.
Thanks!

Joseph

**Comment by cultcom** [comment]
Thank you for your quick response. It seem to be working again.
